- name: ECR Login
  shell: "aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin 354285753755.dkr.ecr.ap-southeast-1.amazonaws.com"
  args:
    executable: /bin/bash
  tags:
    - docker_base_image
- name: Create Docker Build DIR - Base
  file:
    path: "./ansible_managed/docker_build/base"
    state: directory
    mode: '0755'
  tags:
    - docker_base_image
- name: Generate Dockerfile - Base
  template:
    src: docker-file.j2
    dest: "./ansible_managed/docker_build/base/Dockerfile"
  tags:
    - docker_base_image
- name: Build Docker Image - Base
  docker_image:
    build:
      path: "./ansible_managed/docker_build/base"
    name: "354285753755.dkr.ecr.ap-southeast-1.amazonaws.com/prod-munna:local"
    push: no
    state: present
    source: build
  tags:
    - docker_base_image
  notify:
    - Tag Image and Push to ECR [LATEST]      
