#- import_tasks: docker-image-build.yaml
#  when: module != "base-image"
- import_tasks: docker-base-image-build.yaml
  when: module == "base-image"
#- import_tasks: docker-kubectl-runner-image-build.yaml
#  when: module == "kubectl-runner"
